name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            python-version: 3.8
            ros-distro: noetic
    steps:
    - uses: actions/checkout@v2
      with:
        path: package
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install ROS
      uses: suddrey-qut/setup-ros@master
      with:
        required-ros-distributions: ${{ matrix.ros-distro }}
    - name: Build Release
      uses: suddrey-qut/release-tools-ros@master
      id: build
      with:
        ros-distro: ${{ matrix.ros-distro }}
    - name: Upload binaries to release
      uses: suddrey-qut/upload-release-action@master
      id: upload
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        files: ${{ steps.build.outputs.files }}
        tag: ${{ github.ref }}
    - name : Notify QCR
      uses: suddrey-qut/invoke-qcr-hook@master
      with:
        ref: ${{ github.ref }}
        repo: ${{ github.repository }}
        files: ${{ steps.upload.outputs.browser_download_urls }}
    
        
